apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::586794480827:role/eksctl-expense-cluster-1-nodegroup-NodeInstanceRole-1gtj5eZ3p1Rb
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::586794480827:user/meerjan1
      username: meerjan1
    - groups:
      - expense-admin
      userarn: arn:aws:iam::586794480827:user/meerjan2
      username: meerjan2

kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-09T16:22:01Z"
  name: aws-auth
  namespace: kube-system
  uid: b31772b7-e5cd-4e6d-8101-e31526e675dd