apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::586794480827:role/eksctl-expense-cluster-1-nodegroup-NodeInstanceRole-A1pUZ7HSzXqx
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
      - groups:
      - expense-cluster
      userarn: arn:aws:iam::586794480827:user/meerjan
      username: meerjan
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-08T16:17:46Z"
  name: aws-auth
  namespace: kube-system
  uid: 54955a4a-3492-4085-97b1-4ecc1545fbad