# Cluster Role and ClusterRoleBinding for expense project
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expense-cluster-1
rules:
- apiGroups: [""]
  resources: ["nodes","persistentvolumes","namespaces"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: expense-cluster-1
subjects:
- kind: User
  name: meerjan3 # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: expense-cluster-1
  apiGroup: rbac.authorization.k8s.io